### ISSUE TITLE
Fix package.json for TypeScript

### ISSUE THREAD

**Issue by webJose** [zzc6332/worker-handler#5]
Publint says it better than me:  https://publint.dev/worker-handler@0.2.1

**Comment by zzc6332** [comment]
Thanks for pointing out this issue, I’ll look into it and work on a fix as soon as possible.

**Comment by webJose** [comment]
Thanks.  Just a note on open source handling:  You should only close an issue when you have merged a fix that solves it.  Closing issues before is confusing.

Thanks for the hard work.

**Comment by zzc6332** [comment]
Thanks for your note. 
The fixed version has been published on: https://www.npmjs.com/package/worker-handler/v/0.2.2
I am new to open source and pardon my irregular handling. Thanks again for pointing out the issue.
